### ISSUE TITLE
getLampJSONData not working

### ISSUE THREAD

**Issue by AArnao** [lp1dev/OpeniHomma-Client#1]
Hi! first of all nice work!

I'm trying your lib but when I try to get data from my lamp on this way
address = probeDevices()
packet = getLampJSONData()
sendTCPPacket(address, packet, True)

I'm getting a timeout event

Do you know what could go wrong?

Thanks! :)

**Comment by lp1dev** [comment]
Hi ! Thanks a lot!
Could you please check what is returned by probeDevices()?
It's not impossible that your device was not detected on the network

**Comment by AArnao** [comment]
Hi! i got this
Device discovered : b'HLK_A8EA96' 10.0.22.44
('10.0.22.44', 8080)

**Comment by lp1dev** [comment]
Great ! If you have netcat installed on your machine could you please try to connect with it on the port 8080 of this ip? And check it you also have a timeout error
`nc <IP> 8080`

**Comment by AArnao** [comment]
ye it seems like so. Got timeout

**Comment by lp1dev** [comment]
Mh Interesting! It seems that your network or (most likely) device doesn't allow communication on this port. May I know which device you trying to communicate with?

**Comment by AArnao** [comment]
ye is a Mac Mini

**Comment by lp1dev** [comment]
Sorry. I meant with iHomma device are you using :)?

**Comment by AArnao** [comment]
oh (facePalm) xD is Basic RFR3

**Comment by AArnao** [comment]
oh (facePalm) xD is RGB led
https://www.amazon.es/iHomma-Impermeable-Multicolores-2700-6500K-iluminaci%C3%B3n/dp/B073TSY4HJ/ref=sr_1_91?__mk_es_ES=%C3%85M%C3%85%C5%BD%C3%95%C3%91&keywords=Rgb+Led+Wifi&qid=1565768541&s=gateway&sr=8-91

**Comment by lp1dev** [comment]
Haha, that's the one I also worked with, the port should be the same!
 Mmh would you by any chance be able to scan the lamp's open ports with nmap?

**Comment by AArnao** [comment]
Yes i could scan and get this:
Scanning 10.0.22.44 [1000 ports]
Discovered open port 8080/tcp on 10.0.22.44

**Comment by lp1dev** [comment]
Mh weird! It should work, did you try another function? setCustomColor(255, 100, 100) maybe?

**Comment by AArnao** [comment]
yes all other functions worked thats why i thougth it was an error. I will check my network again in case is blocking any incomming packet

**Comment by AArnao** [comment]
after checking my network, didn't find anything weird. Still working on trying to find out why i can't get data back :(

**Comment by lp1dev** [comment]
Hey Aarnao ! Sorry about the delay. I checked and there is something wrong on my code's side. I don't know exactly what yet, I have to debug :/. 
It used to work well but it seems to be broken now, there might be something wrong with the way I pad the bytes I send.

Thanks for reporting the issue! I'll let you know when I find what the problem is

**Comment by AArnao** [comment]
Thanks for your effort! :D 
I will keep a look on it

**Comment by lp1dev** [comment]
Hey :), I updated the client, could you check if the issue is resolved on your end?

**Comment by AArnao** [comment]
Still not resolved :(

I saw your changes and already did something on color-packets build. I realized that packet must be over 1011 always so i did this (in node js)

function buildInstruction(instruction, write_switch, data, final_byte = 0) {
    const header = [0xfe, 0xef];
    const msg_length = data.length + 3;
    const packet = header.concat([msg_length, instruction, write_switch]).concat(data);
    let packet_size = 0;
    let last_byte = 0;
    packet.forEach((byte) => {
        packet_size += byte;
    });

    // Adjust packet size to work with custom colors
    if (instruction === 0xa1 && packet_size < 1011) {
        final_byte = 1011 - packet_size - 1;
        packet_size += final_byte + 1;
    }

    var index;
    for (index in PACKET_SIZES) {
        let size = PACKET_SIZES[index];
        if (size >= packet_size) {
            last_byte = size - packet_size + (final_byte !== 0 ? 1 : 0);
            if (last_byte > 255) {
                continue;
            }

            packet.push(last_byte);
            if (final_byte !== 0) {
                packet.push(final_byte);
            }

            return toBuffer(packet);
        }
    }

    packet.push(final_byte)
    return toBuffer(packet);
}

With this, color can always be set with customColor function without any final_byte needed

**Comment by lp1dev** [comment]
Oh, if you're into JS I've made a Ionic version with TypeScript code (https://github.com/lp1dev/smartlight-manager) !

Could you please try this version (https://gist.github.com/lp1dev/524983941436bad08cdbe9f7e7110b7a) of the client.py file (you can directly run `python client.py`, I added the code to get JSON data in the end of this file directly) ? For some reason, this version works 99% of the time, but the one in the repo only 1% of the time, and they're very very similar. I still didn't find the significative difference
